# Generated by Django 4.1.7 on 2023-02-28 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
    ]
