# Generated by Django 4.1.7 on 2023-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_created_at_course_price_lecture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="keywords",
            field=models.ManyToManyField(related_name="courses", to="courses.keyword"),
        ),
    ]
