# Generated by Django 4.1.7 on 2023-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_keyword_course_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="content",
            field=models.TextField(default="asdasdcontent"),
            preserve_default=False,
        ),
    ]
